# Generated by Django 4.1 on 2022-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('1', 'Acoustic guitar'), ('2', 'Electric guitar'), ('3', 'Acoustic bass'), ('4', 'Electric bass'), ('5', 'Fretless guitar'), ('6', 'Fretless bass')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('string', models.IntegerField(default=6)),
                ('released', models.BooleanField()),
            ],
        ),
    ]
