# Generated by Django 4.1 on 2022-08-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_guitar_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='kind',
            field=models.CharField(choices=[('1', 'Acoustic guitar'), ('2', 'Electric guitar'), ('3', 'Acoustic bass'), ('4', 'Electric bass')], max_length=2),
        ),
    ]
