# Generated by Django 4.1 on 2022-08-31 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_guitar_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='kind',
            field=models.CharField(choices=[('AG', 'Acoustic guitar'), ('EG', 'Electric guitar'), ('MG', 'Multi-string guitar'), ('AB', 'Acoustic bass'), ('EB', 'Electric bass'), ('MB', 'Multi-string bass'), ('CG', 'Classical/Nylon guitar'), ('AR', 'Archtop/Hollow guitar'), ('RE', 'Resonator'), ('SG', 'Stell guitar')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='string',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField(max_length=300)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
