# Generated by Django 4.1 on 2022-09-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_guitar_kind_alter_guitar_string_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='kind',
            field=models.CharField(choices=[('AG', 'Acoustic guitar'), ('EG', 'Electric guitar'), ('MG', 'Multi-string guitar'), ('AB', 'Acoustic bass'), ('EB', 'Electric bass'), ('MB', 'Multi-string bass'), ('CG', 'Classical/Nylon guitar'), ('AR', 'Archtop/Hollow guitar'), ('RE', 'Resonator'), ('SG', 'Steel guitar')], max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
