# Generated by Django 4.1 on 2022-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_player_guitar_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='players',
            field=models.ManyToManyField(blank=True, to='main_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
